---
title: "R-script grønning"
author: "Markus Fjellstad Israelsen"
date: "2023-01-11"
output: word_document
---

Load library
```{r Load Library}

library(countcolors)
library(camtrapR)
library(lubridate)
library(ggplot2)
library(dplyr)
library(writexl)
library(readxl)
library(gridExtra)

```

Set up Green Fraction function
```{r Green Fraction function, echo = TRUE, eval = TRUE}

# YearlyFolderDir = "P:/12179000_lirypetelemetri_i_lierne/ImagesGreenFraction/"
GreenFraction = function(YearlyFolderDir){
  # Import exif tool
  exiftool_dir = "C:/Exiftool/"        
  exiftoolPath(exiftoolDir = exiftool_dir)
  
  # Define the directory for the image folders
  yearFoldersPath = YearlyFolderDir
  yearFoldersLength = list.files(yearFoldersPath)
  
  # For loop over the years
  for(i in 1:length(yearFoldersLength)){
    memCardFolders = list.files(paste0(yearFoldersPath, yearFoldersLength[i]))
    
    # For loop over the memory cards in each year
    for(j in 1:length(memCardFolders)){
      images = list.files(paste0(yearFoldersPath, yearFoldersLength[i], "/", memCardFolders[j]))
      images.db = which(images == "Thumbs.db")
      if(length(images.db) > 0){
        images = images[-images.db]
      }
      imagePath = paste0(yearFoldersPath, yearFoldersLength[i], "/", memCardFolders[j])
      MemCard = substring(imagePath, 76, nchar(imagePath))
      
      # For loop over each image, in each memory card, in each year
      imgDay = c()
      imgDayDF = data.frame("Date" = c(ymd("1970-01-01")), "Time" = "09:00:00", GreenFraction = c(NA), periodTempC = NA)
      tempDF = data.frame("Date" = c(ymd("1970-01-01")), "Time" = "09:00:00", tempC = NA)
      for (k in 1:length(images)){
        imgInfo = exifTagNames(inDir = imagePath, 1, images[k]) # extract image info
        imgDateTime = imgInfo[5, 3] # date and time
        Date = ymd(substring(imgDateTime, 1, 10))
        sTime = substring(imgDateTime, 20, 22) # correcting for summer time
        aTime = substring(imgDateTime, 12, 19)
        nTime = paste0(as.numeric(substring(aTime, 1, 2))+as.numeric(sTime), substring(aTime, 3, 8))
        Time = ifelse(nchar(nTime) == 7, paste0("0",as.numeric(substring(aTime, 1, 2))+as.numeric(sTime), substring(aTime, 3, 8)), nTime)
        tempC = as.numeric(substring(imgInfo[50, 3], 1, 2)) # Degrees centigrade
        tempDF[k, ] = c(as.character(Date), Time, tempC)
        
        # Filter out images in the time period of interest
        if(Time > "06:00:00" & Time < "18:00:00"){
          imgDay = append(imgDay, images[k])
          imgDayDF = rbind(imgDayDF, c(as.character(ymd(Date)), Time, NA, as.numeric(tempC)))
        }
      }
      imgDayDF = imgDayDF[-1, ]
      
      # For loop that extracts the fraction of green in each image
      for(h in 1:length(imgDay)){
    recImgGreenFraction = countcolors::rectangularRange(jpeg::readJPEG(paste0(imagePath, "/", imgDay[h])), upper = c(0.60, 1, 0.4), lower = c(0, 0.4, 0), color.pixels = FALSE, plotting = FALSE)
    recIGF = recImgGreenFraction$img.fraction * 100
    imgDayDF$GreenFraction[h] = recIGF
      }
      
      # Subset data frame based observations from just the whole hour (for instance, 12:00:00, 13:00:00 and so on.)
      imgDayDF = imgDayDF[grep(":00:00", imgDayDF$Time), ] 
      imgDayDF$GreenFraction = as.numeric(imgDayDF$GreenFraction)
      
      # Get the mean/median/min/max temperature for each image
      tempDF$tempC = as.numeric(tempDF$tempC)
      tempDF = tempDF[grep(":00:00", tempDF$Time), ]
      tempDfMean = tempDF %>% group_by(Date) %>% summarise(meanTempC = mean(tempC, na.rm = TRUE), minTempC = min(tempC, na.rm = TRUE), maxTempC = max(tempC, na.rm = TRUE), medianTempC = median(tempC, na.rm = TRUE))
      tempDfMean = tempDfMean %>% dplyr::select(Date, meanTempC, medianTempC, minTempC, maxTempC)
      tempDfMean$Date = as.Date(tempDfMean$Date)
      
      # Take the mean/median/min/max of the green fraction for each day
      imgDayDfMean = imgDayDF %>% group_by(Date) %>% summarise(meanGreenFraction = mean(GreenFraction, na.rm = TRUE), maxGreenFraction = max(GreenFraction, na.rm = TRUE), meanPeriodTempC = mean(as.numeric(periodTempC), na.rm = TRUE), medianPeriodTempC = median(as.numeric(periodTempC), na.rm = TRUE), minPeriodTempC = min(as.numeric(periodTempC), na.rm = TRUE), maxPeriodTempC = max(as.numeric(periodTempC), na.rm = TRUE))
      imgDayDfMean$Date = as.Date(imgDayDfMean$Date)
      imgDayDfMean = left_join(imgDayDfMean, tempDfMean, by = "Date")
      imgDayDfMean = imgDayDfMean %>% mutate(MemCard = MemCard)
      
      ## Export excel tables
      #write_xlsx(imgDayDfMean, paste0("C:/Users/markus.israelsen/OneDrive - NINA/GitHub/LierneGreening/LierneGreening/Output/", "dailyGreen_", substring(yearFoldersLength[i], 14, 17), "_", substring(imagePath, 76, 89), ".xlsx"))
      
    }
  }
}

```

Run the Greening Fraction Function
```{r Run GF function, echo = TRUE, eval = FALSE}

# Supply the function with the directory path where the yearly greening images are stored (Kamerabilder 2019, Kamerabilder 2020..)
s = Sys.time()
GreenFraction(YearlyFolderDir = "P:/12179000_lirypetelemetri_i_lierne/ImagesGreenFraction/")
e = Sys.time()
runTime = e - s
runTime

```

Import all the green fraction datasets and join them
```{r Import DF, echo = TRUE, eval = FALSE}

outputPath = "C:/Users/markus.israelsen/OneDrive - NINA/GitHub/LierneGreening/LierneGreening/Output/"

greenFractionFiles = list.files(outputPath, pattern = "\\.xlsx$")
greenFractionList = lapply(paste0(outputPath, greenFractionFiles), read_excel)
greenFractionDF = bind_rows(greenFractionList) %>% mutate(YearDay = yday(Date), year = year(Date), monthNum = month(Date), month = month.abb[monthNum], day = day(Date))

# Remove all images after 25th of June
#greenFractionDF = greenFractionDF %>% filter(YearDay <= 176)

#write_xlsx(greenFractionDF, "C:/Users/markus.israelsen/OneDrive - NINA/GitHub/LierneGreening/LierneGreening/Output/dailyGreenPixels.xlsx")

```

